### ISSUE TITLE
running on ubuntu?

### ISSUE THREAD

**Issue by Moadab-AI** [HyHydromechanics/Netease-cloud-music-free-Downloader#2]
Hi I tried to run the python script on ubuntu but it fails. is it supposed to work  on linux too or its just intended for windows? also would it work from outside mainland china? does one need to create an account?

**Comment by HyHydromechanics** [comment]
I think the reason why you failed in running the py script is that there's no requests in your pip
Try to use pip to install requests in the terminal.
I think it works wherever you are... as long as you are able to open the website of Netease music, and there's no need to create an account for it.

**Comment by Moadab-AI** [comment]
No, its not a pip issue. I actually had to change some minor things in the .py script to adapt it to linux, like converting .ico to .xbm and changing saving address formats. Now it runs, but the issue is that when I manage to save a mp3 file its a very small sized  (less than 100 kb) file which its turns out  it saves a 404 page response.  i guess it has to do with the fact that im outsside china. :/

**Comment by HyHydromechanics** [comment]
Maybe.... what about try the second button and copy the link into your browser?

**Comment by Moadab-AI** [comment]
that link also leads to a 404 page :/
could you try to see if downloading this track for example works for you if you are in mainland china?:  https://y.music.163.com/m/song?id=1840993562&userid=7982061669&dlt=0846

**Comment by HyHydromechanics** [comment]
<img width="1436" alt="截屏2022-08-11 22 34 12" src="https://user-images.githubusercontent.com/87158955/184158619-eae133d2-d036-485f-aa47-381bc4aaec0f.png">
I guess it is because the Netease music does not provide services in your area

**Comment by Moadab-AI** [comment]
the url above that i sent you of course i can reach. its the output of your code , the url that ends with .mp3 that leads to a 404 page for me. or if i for example click on the download button in the photo above in the app or website gives either error or asks to login ...

**Comment by HyHydromechanics** [comment]
http://m801.music.126.net/20220812064142/347520754aa41b064e647c9c8e8d94e5/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/8708291561/fdba/4427/89f8/11e793334a9d8c648eedbcb05852731e.mp3, are you able to reach this website?

**Comment by HyHydromechanics** [comment]
the original url: https://y.music.163.com/m/song?id=1840993562&userid=7982061669&dlt=0846
convert result: http://music.163.com/song/media/outer/url?id=1840993562&userid=7982061669&dlt=0846.mp3
redirect took place in browser: http://m701.music.126.net/20220812064549/dbfe43b8ba87ac23fb8cc4d0ee8e2e92/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/8708291561/fdba/4427/89f8/11e793334a9d8c648eedbcb05852731e.mp3

**Comment by HyHydromechanics** [comment]
Basically, my code's job is to get the song's id, and convert it into an incoming link and with redirects of url, the incoming link is able to be downloaded

**Comment by Moadab-AI** [comment]
> the original url: https://y.music.163.com/m/song?id=1840993562&userid=7982061669&dlt=0846 convert result: http://music.163.com/song/media/outer/url?id=1840993562&userid=7982061669&dlt=0846.mp3 redirect took place in browser: http://m701.music.126.net/20220812064549/dbfe43b8ba87ac23fb8cc4d0ee8e2e92/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/8708291561/fdba/4427/89f8/11e793334a9d8c648eedbcb05852731e.mp3

Thanks. I see. I cant even access the .mp3 urls you have listed and keep getting the 404 page. Now I'm sure the issue is IP block.

**Comment by HyHydromechanics** [comment]
Fine...
